# Generated by Django 5.1 on 2024-09-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_original', models.CharField(max_length=255)),
                ('nome_traduzido', models.CharField(max_length=255)),
                ('afiliacao_original', models.CharField(max_length=255)),
                ('afiliacao_traduzida', models.CharField(max_length=255)),
            ],
        ),
    ]
